name: create infra azure terraform github action 
on: 
  push:
    branchs:
      - feature

permissions:
  id-token: write
  contents: read
jobs:
  Azure-Terraform:
    runs-on: ubuntu-latest

    # Checkout the repository to the GitHub Actions runner
    
      
    steps:
    

    - name: azure login
      uses: azure/login@v1
      with:
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }} 
        subscription_id: ${{ secrets.AZURE_SUBSCRITION_ID}}
        
         
    - name: Dummy Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az group list
          pwd
