name: create infra azure terraform github action 
on: 
  push:
    branchs:
      - feature

permissions:
  id-token: write
  contents: read
jobs:
  Azure-Terraform:
    runs-on: ubuntu-latest

    # Checkout the repository to the GitHub Actions runner
    
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: azure login
      uses: azure/login@v3
      with:
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }} 
        subscription_id: ${{ secrets.AZURE_SUBSCRITION_ID}}
        
         
    - name: verify azure login
      run: |
        
        az account show
        az account list
